### ISSUE TITLE
calculate the angles between robotpose and global plan point pose

### ISSUE THREAD

**Issue by yamfeng** [asr-ros/asr_ftc_local_planner#10]
in ftc_planner.cpp,lin239,when you calculate the angles between robotpose and global plan point pose, should the x_pose be transformed_global_plan_.at(i) or transformed_global_plan_.at(point)?

double FTCPlanner::calculateGlobalPlanAngle(tf::Stamped<tf::Pose> current_pose, const std::vector<geometry_msgs::PoseStamped>& plan, int point)
    {
        if(point >= (int)plan.size())
        {
            point = plan.size()-1;
        }
        double angle = 0;
        double current_th = tf::getYaw(current_pose.getRotation());
        for(int i = 0; i <= point; i++)
        {
            geometry_msgs::PoseStamped x_pose;
            x_pose=transformed_global_plan_.at(point);

            //Calculate the angles between robotpose and global plan point pose
            double angle_to_goal = atan2(x_pose.pose.position.y - current_pose.getOrigin().getY(),
                                         x_pose.pose.position.x - current_pose.getOrigin().getX());
            angle += angle_to_goal;
        }

        //average
        angle = angle/(point+1);

        return angles::shortest_angular_distance(current_th, angle);
    }

**Comment by FelixMarek** [comment]
Hi,
yes this is a failure. It should be x_pose be transformed_global_plan_.at(i) and not  transformed_global_plan_.at(point)
