### ISSUE TITLE
'global_costmap_ros_' was not declared in this scope

### ISSUE THREAD

**Issue by drscopus** [asr-ros/asr_ftc_local_planner#2]
Hi, when I compile asr_ftc_local_planner  by running catkin_make, it output 
```
error: 'global_costmap_ros_' was not declared in this scope
             joinCostmap_->initialize(costmap_ros_, global_costmap_ros_);
```

Where the variable 'global_costmap_ros_' is declared? 
Thanks

**Comment by FelixMarek** [comment]
Hi,
you must define this parameter in the nav_core package. 
Look at the wiki [http://wiki.ros.org/asr_ftc_local_planner](http://wiki.ros.org/asr_ftc_local_planner) at point "3.1. Needed packages" at under point "nav_core".

You must add one protected attribute:
_costmap_2d::Costmap2DROS* global_costmap_ros_;
in nav_core/include/base_local_planner.h

Or you can use our nav_core packages at [https://github.com/asr-ros/asr_nav_core/tree/master/include/nav_core](https://github.com/asr-ros/asr_nav_core/tree/master/include/nav_core).
