### ISSUE TITLE
The robot move back and forth for a long time 

### ISSUE THREAD

**Issue by yumingdong** [asr-ros/asr_ftc_local_planner#4]
I have used the asr_ftc_local_planner as the base_local_planner, and under  instructions from [http://wiki.ros.org/asr_ftc_local_planner](url).  But in the simulation of  my differential robot, I found that robot is always move back and forth, and have a long time to adhere the goal position. And I tune some parameters of "asr_ftc_local_planner", for example tune  the **max_rotation_vel** and "**acceleration_x**" or "**acceleration_z**", but it didn't  work ([http://wiki.ros.org/asr_ftc_local_planner/FindRightParameters](url) ). I also run "**roslaunch asr_mild_navigation simulation_manual_rearranged.launch**", it also has the same problem.

**Comment by FelixMarek** [comment]
Hi,
it could come from, that your position_accuracy is to small/accuracy. Or your position_accuracy is to small in relation to your acceleration_x, because the robot slow down with this factor. Decrease the acceleration_x or increase the position_accuracy value. 
If it not work, please pose all of your parametes.

**Comment by yumingdong** [comment]
Well, I have some increase the position_accuracy value and decrease the acceleration_x, the robot go forward a small distance, and then it trigger the  recovery_behavior of move_base,and it loops until it has reached the goal. I use the move_base package, and I have make some correction of move_base.cpp and base_local_planner.h under the instruction from [http://wiki.ros.org/asr_ftc_local_planner](url). Here is my simulation parameters:
`join_obstacle: false
  local_planner_frequence: 5.0
  max_rotation_vel: 0.6
  min_rotation_vel: 0.1
  max_x_vel: 0.3
  acceleration_x: 0.2
  acceleration_z: 0.5
  position_accuracy: 0.15
  rotation_accuracy: 0.3
  sim_time: 0.75
  slow_down_factor: 2.5`

**Comment by FelixMarek** [comment]
Hm. The ftc_planner doesnt use the move_base recovery_behavior. Be sure, that your goal pose isn't to near at obstacels. This could couse this behavior. 
Also could the global costmap resolution be to small (To big pixel of the costmap). Or the global planner loose the global plan (does't find a plan). 

Are you see in Rviz the global planner and ftc planner visualization. What see you, when the robot go to recovery behavior, and what you see it is near the goal (Do you always see the global plan?). Is the goal always on the same position?

Are there any outputs (ROS_INFOS, ROS_WARN) in the console?

**Comment by yumingdong** [comment]
Yes, I am sure the goal of my robot isn't adhere to the local obstacles, the resolution of my global costmap is 0.05. By the way, the global path is always keep , and I can see the global plan in rviz. The local path in rviz is also be seen. In the terminal, the ftc_local_planner often has following imply:
     **FTCPlanner: Excessive deviation from global plan orientation. Start routine new.**

Here is my recorded video of such state,  [https://drive.google.com/open?id=1kM6f82pTaxhH1kqBTw8IMzDviKlVzy2Y](url). 
In this video the green line is the global path, and the red line is the local path, the simulated robot is always move back and forth,but never get the goal.

**Comment by FelixMarek** [comment]
At this video the problem is, that the global plan isn't updatet. 
Set the "planner_frequency" paramater, at the move_base to 3.
You can see an example at [https://github.com/asr-ros/asr_mild_navigation/blob/master/launch/simulation/simulation.launch](https://github.com/asr-ros/asr_mild_navigation/blob/master/launch/simulation/simulation.launch)
