### ISSUE TITLE
obstacle avoidance?

### ISSUE THREAD

**Issue by aarontan-git** [asr-ros/asr_ftc_local_planner#5]
Hello,

Just to confirm, this local planner doesnt have obstacle avoidance built in?

It's role is to follow a global plan that is predefined with considerations of known obstacles already?

Thanks

**Comment by FelixMarek** [comment]
Yes, this is that what the planner do.

If the global planner can dynamicly recognize obstacles, the robot will drive around them.
The ftc planner doesnt contain a own obstacle regonizion.
