### ISSUE TITLE
error:move_base

### ISSUE THREAD

**Issue by sweetquiet** [asr-ros/asr_ftc_local_planner#6]
hello:

terminate called after throwing an instance of 'boost::exception_detail

move_base has died

**Comment by FelixMarek** [comment]
Can you show me the hole output? Is move_base also dieing if you don't call the boost:: exception_detail?

Have you use an other navigation before, and is there also the exception?

**Comment by sweetquiet** [comment]
first thank you very much!
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
其余的导航也用过  比如：dwa teb ,这个按照你的教程改完都能够正常运行， 但是一旦发送目标点就会出现上边的错误，然后是move_base has died, boost::exception_detail 我也没找到谁调用的，你知道怎么关闭吗    thank you very much

**Comment by sweetquiet** [comment]
auto-starting new master
process[master]: started with pid [27982]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to df2081a8-c48b-11e8-926a-a0c589ab7b06
process[rosout-1]: started with pid [27995]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [28012]
process[robot_joystick-3]: started with pid [28013]
process[joystick-4]: started with pid [28014]
process[broadcast1-5]: started with pid [28026]
process[broadcast2-6]: started with pid [28042]
process[broadcast3-7]: started with pid [28052]
process[robot_drive-8]: started with pid [28060]
process[twist_to_motors-9]: started with pid [28070]
process[motors_to_cmds-10]: started with pid [28080]
process[odom_node-11]: started with pid [28086]
process[imu-12]: started with pid [28097]
process[robot_pose_ekf-13]: started with pid [28099]
process[pose_to_odom-14]: started with pid [28102]
process[urg_node-15]: started with pid [28119]
process[map_server-16]: started with pid [28131]
process[amcl-17]: started with pid [28139]
process[nodelet_manager-18]: started with pid [28149]
[ INFO] [1538296567.300105111]: Opened joystick: /dev/input/js0. deadzone_: 0.050000.
process[velocity_smoother-19]: started with pid [28165]
process[move_base-20]: started with pid [28175]
process[rviz-21]: started with pid [28177]
[ INFO] [1538296567.643536250]: Connected to serial device with ID: H1629778
[ INFO] [1538296567.866396584]: Starting calibration. This will take a few seconds.
[ WARN] [1538296567.866479735]: Time calibration is still experimental.
[INFO] [1538296567.923515]: /twist_to_motors started
[INFO] [1538296568.099238]: /motors_to_cmds started
[INFO] [1538296568.842040]: -I- /odom_node started
[ INFO] [1538296568.889585018]: Calibration finished. Latency is: -0.0202.
[INFO] [1538296568.932762]: Starting with serial port: /dev/imu, baud rate: 115200
[INFO] [1538296568.934287]: If the serial is opened: 1
[INFO] [1538296568.934645]: Reset!
[ INFO] [1538296569.013192478]: Streaming data.
[INFO] [1538296569.892347]: True
[INFO] [1538296569.935603]: sleep 1 second
[ INFO] [1538296570.182426386]: Using plugin "static_layer"
[ INFO] [1538296570.225318440]: Requesting the map...
[ INFO] [1538296570.435188515]: Resizing costmap to 1257 X 603 at 0.050000 m/pix
[ INFO] [1538296570.534386627]: Received a 1257 X 603 map at 0.050000 m/pix
[ INFO] [1538296570.544240024]: Using plugin "obstacle_layer"
[ INFO] [1538296570.550321645]:     Subscribed to Topics: scan bump
[ INFO] [1538296570.656956679]: Using plugin "inflation_layer"
[ INFO] [1538296570.819986340]: Using plugin "obstacle_layer"
[ INFO] [1538296570.823514871]:     Subscribed to Topics: scan bump
[ INFO] [1538296570.912150324]: Using plugin "inflation_layer"
[ INFO] [1538296571.005826143]: Created local_planner ftc_local_planner/FTCPlanner
[ INFO] [1538296571.052004985]: FTCPlanner: Version 2 Init.
[ INFO] [1538296571.052047282]: already enter new planner++++++++++++++++++++++
[ INFO] [1538296571.104580453]: Recovery behavior will clear layer obstacles
[ INFO] [1538296571.112167706]: Recovery behavior will clear layer obstacles
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

**Comment by FelixMarek** [comment]
Ok. Can you also show me your movebase and ftc planner Parameter.
This error could be caused because the parallel use of the local costmap from ftc planner and costmapmodul.
If you have set the ftc planner Parameter "join_obstacle" to true, set it to false and test it again.

**Comment by sweetquiet** [comment]
OK 
++++++++++++move_base++++++++++++++++
shutdown_costmaps: false
controller_frequency: 5.0
controller_patience: 15.0
planner_frequency: 5.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2 #0.2

base_global_planner: "global_planner/GlobalPlanner" 
base_local_planner: "ftc_local_planner/FTCPlanner"

++++++++++++++++++++++++ftc_params+++++++++++++++++++++++++++++
FTCPlanner:
  max_x_vel: 0.5
  max_rotation_vel: 1.0
  min_rotation_vel: 0.4
  acceleration_x: 0.5
  acceleration_z: 0.5
  position_accuracy: 0.04
  rotation_accuracy: 0.03
  slow_down_factor: 2.5
  sim_time: 0.6
  local_planner_frequence: 5
  join_obstacle: false

**Comment by sweetquiet** [comment]
Hello

I find that the move_base is a little different from the move_base you provide. boost:: mutex is different from boost:: recursive_mutex, but it shouldn't go wrong. 

Good luck

**Comment by FelixMarek** [comment]
It could be that newer (or older versions) of move_base use other mutex.
I don't think this problem comes from ftc planner. There is no mutex in ftc. You can only try to increase the calculation frequence of the global planner, so that it is higher than the local planner frequence.

**Comment by sweetquiet** [comment]
ok
Let me try it.

**Comment by sweetquiet** [comment]
Hello

It's no use changing frequency. Haven't you met before? What version of ROS did you use before? Thank you.

**Comment by FelixMarek** [comment]
No i haven't seen this issue before. The ftc planner is tested under ROS indigo and kinetic. 
I cant reproduce this issue.
If it is caused because the ftc planner it could only be a thing of the global plan with is used in the ftc planner. You can check if you use the plan somewhere else. Or you can delte, for a test, the mutex of te global plan.

**Comment by sweetquiet** [comment]
Okay

I forgot to tell you. Your FTCPlanner:: global_costmap_ros_ forgot to define in header file, resulting in compilation error.

**Comment by FelixMarek** [comment]
Sorry, I cant find the error. It has to have something to to, with one other component of your project, or with some specific interactions between the ftc planner and your code.

**Comment by sweetquiet** [comment]
Hello, I changed a computer to try today, and found that there is no problem with normal operation, but with the original computer run the rest of the local_planner normal, but running FTC will lead to move_base died, this thing really henguiyia
