### ISSUE TITLE
move_base error

### ISSUE THREAD

**Issue by longjianquan** [asr-ros/asr_ftc_local_planner#7]
[ INFO] [1539916609.299189745, 2.000000000]: Using plugin "inflation_layer"
[ INFO] [1539916609.327095177, 2.100000000]: Created local_planner ftc_local_planner/FTCPlanner
[ INFO] [1539916609.344824725, 2.100000000]: FTCPlanner: Version 2 Init.
[ INFO] [1539916609.624119869, 2.400000000]: Recovery behavior will clear layer obstacles
[ INFO] [1539916609.630263433, 2.400000000]: Recovery behavior will clear layer obstacles
[ INFO] [1539916627.121642413, 19.900000000]: 111
[move_base-10] process has died [pid 31749, exit code -11, cmd /home/ljq/catkin_ws/devel/lib/move_base/move_base cmd_vel:=navigation_velocity_smoother/raw_cmd_vel odom:=odom scan:=scan __name:=move_base __log:=/home/ljq/.ros/log/d24b6b58-d347-11e8-878a-1c1b0daf1897/move_base-10.log].
log file: /home/ljq/.ros/log/d24b6b58-d347-11e8-878a-1c1b0daf1897/move_base-10*.log

**Comment by FelixMarek** [comment]
Can you check where the ROS_INFO "Recovery behavior will clear layer obstacles" comes from? 

Have you adapt move_base and nav_core like it is descripes in the wiki?
