### ISSUE TITLE
Question regarding two wheels velocity

### ISSUE THREAD

**Issue by abylikhsanov** [asr-ros/asr_ftc_local_planner#9]
I have tried your local planner and I would prefer to use rather than dwa. I just have one question regarding the algorithm, it seems that it does not post linear.x + angular.z velocities at the same time, is it designed to be like that? So in curvy path (using Djikstra as a global planner) local planner publishes only angular commands and no linear so robot drifts side to side and only if there is a straight path, robot drives straight.

**Comment by FelixMarek** [comment]
The planner calculates x and z velocities at the same time. Only at the Beginning and the end of the path the robot will rotate on the place. 
It could be that you must use other parameters for your robot. 
Check if the sim_time parameter is right. Therforce you can see the visualisation of the local plan in RVIZ and see if the local plan is to long or to short.
